# Generated by Django 4.1.7 on 2024-11-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailregistration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='emailregistration',
            unique_together={('email', 'book')},
        ),
    ]
